SCREEN_X_SIZE = 1280
SCREEN_Y_SIZE = 900

GAME_FPS = 54

''' Game settings '''

# Players

PLAYER_COLORS = [[2, 82, 8], [1, 79, 135]]
PLAYER_IMAGES = ["player_team_0.png", "player_team_1.png"]
PLAYER_CONTROLLED_IMAGE = "controlled_player.png"

PLAYER_RADIUS = 15
PLAYER_AREA_RADIUS = 15
PLAYER_AREA_RADIUS_MEASUREMENT_ERROR = 0.003

DEFAULT_SPEED = 3.5
DEFAULT_POWER = 10
DEFAULT_CATCH_RADIUS = 1

CONTROLLED_SPEED = 4.5
CONTROLLED_POWER = 14
CONTROLLED_CATCH_RADIUS = 1

BIG_RADIUS = 10000

PLAYER_NUMBER_FONT = "Comic Sans MS"
PLAYER_NUMBER_FONT_SIZE = 30

# Ball

BALL_RADIUS = 14
BALL_DIST_TO_OWNER = 1
BALL_SPEED_REGRESSION = 0.1
BALL_IMAGE = "ball.png"

''' Field settings '''

FIELD_IMAGE = "new_field.png"
FIELD_BLURED_IMAGE = "new_field_blured.png"

GATES = [[[85, 365], [85, 530]],
         
         [[1195, 365], [1195, 530]]]

GATES_CENTER = [
    [(GATES[0][0][0] + GATES[0][1][0]) // 2, (GATES[0][0][1] + GATES[0][1][1]) // 2],
    [(GATES[1][0][0] + GATES[1][1][0]) // 2, (GATES[1][0][1] + GATES[1][1][1]) // 2]
]

CORNERS = [
    [85, 80], [1195, 80],
    [1195, 830], [85, 830]
]

FIELD_CENTER = [
    (CORNERS[0][0] + CORNERS[2][0]) // 2,
    (CORNERS[0][1] + CORNERS[2][1]) // 2
]

FIELD_SIZE_X = SCREEN_X_SIZE - CORNERS[0][0] - (SCREEN_X_SIZE - CORNERS[2][0])
FIELD_SIZE_Y = SCREEN_Y_SIZE - CORNERS[0][1] - (SCREEN_Y_SIZE - CORNERS[2][1])

SCOREBOARD_IMAGE = "scoreboard.png"
SCOREBOARD_SIZE_X = 120
SCOREBOARD_SIZE_Y = 80
SCOREBOARD_FONT = "joystix-monospace.ttf"
SCOREBOARD_FONT_SIZE = 30

SCOREBOARD_GOALS_0_X_OFFSET = 33
SCOREBOARD_GOALS_0_Y_OFFSET = 50
SCOREBOARD_GOALS_1_X_OFFSET = 87
SCOREBOARD_GOALS_1_Y_OFFSET = 50

''' Button settings '''

BTN_FONT = "Comic Sans MS"
BTN_FONT_SIZE = 84
BTN_IMAGE = "btn.png"

''' Menu settings '''

MAIN_MENU_BACKGROUND_IMAGE = "new_field_blured.png"

MAIN_MENU_CENTER_INDENT = -100
MENU_BTN_SIZE_X = 600
MENU_BTN_SIZE_Y = 200
MENU_BTN_Y_PADDING = 20

''' Static and media files '''

STATIC_IMAGES_FOLDER = "static/images/"
STATIC_FONTS_FOLDER = "static/fonts/"


''' Game modes config '''

GAMEMODE_UNLIMITED_5v5_TEAM_SIZE = 6
GAMEMODE_UNLIMITED_5v5_GOALKEEPERS_COUNT = 1
GAMEMODE_UNLIMITED_5v5_DEFENDERS_COUNT = 2
GAMEMODE_UNLIMITED_5v5_WINGERS_COUNT = 2
GAMEMODE_UNLIMITED_5v5_STRIKERS_COUNT = 1

GAMEMODE_UNLIMITED_3v3_TEAM_SIZE = 4
GAMEMODE_UNLIMITED_3v3_GOALKEEPERS_COUNT = 1
GAMEMODE_UNLIMITED_3v3_DEFENDERS_COUNT = 1
GAMEMODE_UNLIMITED_3v3_WINGERS_COUNT = 1
GAMEMODE_UNLIMITED_3v3_STRIKERS_COUNT = 1

''' Popup settings '''

POPUP_FONT = "joystix-monospace.ttf"
POPUP_FONT_SIZE = 240

POPUP_BTN_CENTER_INDENT = 150
POPUP_BTN_Y_PADDING = 20

POPUP_GOAL = "GOAL"
POPUP_GOAL_TICKS = 120

POPUP_BALL_OUT = "OUT"
POPUP_BALL_OUT_TICKS = 80

''' Replay settings '''

REPLAY_BTN_SIZE_X = 500
REPLAY_BTN_SIZE_Y = 120

REPLAY_SAVED_SECS = 4

REPLAY_FIELD_TEXT = "REPLAY"
REPLAY_FIELD_TEXT_FONT = "joystix-monospace.ttf"
REPLAY_FIELD_TEXT_SIZE = 160

''' Bot logic '''

# General

BOT_DISALLOWED_MOVE_RADIUS = 4
BOT_MIN_DIST_TO_PASS = 150
BOT_MAX_DIST_TO_PASS = 350

# Defender

BOT_DEFENDER_TEAM_0_BOX_CORNERS = [
    [[CORNERS[0][0] + 15, CORNERS[0][1]], 
    [CORNERS[0][0] + FIELD_SIZE_X // 3, CORNERS[0][1] + FIELD_SIZE_Y // 2]],

    [[CORNERS[0][0] + 15, CORNERS[0][1] + FIELD_SIZE_Y // 2], 
    [CORNERS[0][0] + FIELD_SIZE_X // 3, CORNERS[0][1] + FIELD_SIZE_Y]]
]

BOT_DEFENDER_TEAM_1_BOX_CORNERS = [
    [[CORNERS[2][0] - FIELD_SIZE_X // 3, CORNERS[0][1]],
    [CORNERS[2][0] - 15, CORNERS[0][1] + FIELD_SIZE_Y // 2]],
                                     
    [[CORNERS[2][0] - FIELD_SIZE_X // 3, CORNERS[0][1] + FIELD_SIZE_Y // 2],
    [CORNERS[2][0] - 15, CORNERS[0][1] + FIELD_SIZE_Y]]
]

BOT_DEFENDER_TEAM_0_INITIAL_POS = [
    [(BOT_DEFENDER_TEAM_0_BOX_CORNERS[0][0][0] + BOT_DEFENDER_TEAM_0_BOX_CORNERS[0][1][0]) // 2,
    (BOT_DEFENDER_TEAM_0_BOX_CORNERS[0][0][1] + BOT_DEFENDER_TEAM_0_BOX_CORNERS[0][1][1]) // 2],

    [(BOT_DEFENDER_TEAM_0_BOX_CORNERS[1][0][0] + BOT_DEFENDER_TEAM_0_BOX_CORNERS[1][1][0]) // 2,
    (BOT_DEFENDER_TEAM_0_BOX_CORNERS[1][0][1] + BOT_DEFENDER_TEAM_0_BOX_CORNERS[1][1][1]) // 2],
]

BOT_DEFENDER_TEAM_1_INITIAL_POS = [
    [(BOT_DEFENDER_TEAM_1_BOX_CORNERS[0][0][0] + BOT_DEFENDER_TEAM_1_BOX_CORNERS[0][1][0]) // 2,
    (BOT_DEFENDER_TEAM_1_BOX_CORNERS[0][0][1] + BOT_DEFENDER_TEAM_1_BOX_CORNERS[0][1][1]) // 2],

    [(BOT_DEFENDER_TEAM_1_BOX_CORNERS[1][0][0] + BOT_DEFENDER_TEAM_1_BOX_CORNERS[1][1][0]) // 2,
    (BOT_DEFENDER_TEAM_1_BOX_CORNERS[1][0][1] + BOT_DEFENDER_TEAM_1_BOX_CORNERS[1][1][1]) // 2],
]

BOT_DEFENDER_DIST_TO_ATTACKER_TO_PASS = 300
BOT_DEFENDER_MIN_DIST_TO_TEAMMATE_TO_PASS = 100
BOT_DEFENDER_MAX_DIST_TO_TEAMMATE_TO_PASS = 250

# Winger

BOT_WINGER_TEAM_0_BOX_CORNERS = [
    [[CORNERS[0][0] + 160, CORNERS[0][1]],
    [CORNERS[2][0] - 160, CORNERS[0][1] + FIELD_SIZE_Y // 2 - 120]],

    [[CORNERS[0][0] + 160, CORNERS[0][1] + FIELD_SIZE_Y // 2 + 120],
    [CORNERS[2][0] - 160, CORNERS[2][1]]]
]
BOT_WINGER_TEAM_1_BOX_CORNERS = [
    [[CORNERS[0][0] + 160, CORNERS[0][1]],
    [CORNERS[2][0] - 160, CORNERS[0][1] + FIELD_SIZE_Y // 2 - 120]],

    [[CORNERS[0][0] + 160, CORNERS[0][1] + FIELD_SIZE_Y // 2 + 120],
    [CORNERS[2][0] - 160, CORNERS[2][1]]]
]

BOT_WINGER_TEAM_0_INITIAL_POS = [
    [BOT_WINGER_TEAM_0_BOX_CORNERS[0][0][0] + (BOT_WINGER_TEAM_0_BOX_CORNERS[0][1][0] - BOT_WINGER_TEAM_0_BOX_CORNERS[0][0][0]) // 3,
    BOT_WINGER_TEAM_0_BOX_CORNERS[0][0][1] + (BOT_WINGER_TEAM_0_BOX_CORNERS[0][1][1] - BOT_WINGER_TEAM_0_BOX_CORNERS[0][0][1]) // 3],

    [BOT_WINGER_TEAM_0_BOX_CORNERS[1][0][0] + (BOT_WINGER_TEAM_0_BOX_CORNERS[1][1][0] - BOT_WINGER_TEAM_0_BOX_CORNERS[1][0][0]) // 3,
    BOT_WINGER_TEAM_0_BOX_CORNERS[1][0][1] + (BOT_WINGER_TEAM_0_BOX_CORNERS[1][1][1] - BOT_WINGER_TEAM_0_BOX_CORNERS[1][0][1]) // 3],
]
BOT_WINGER_TEAM_1_INITIAL_POS = [
    [BOT_WINGER_TEAM_1_BOX_CORNERS[0][0][0] + (BOT_WINGER_TEAM_1_BOX_CORNERS[0][1][0] - BOT_WINGER_TEAM_1_BOX_CORNERS[0][0][0]) * 2 // 3,
    BOT_WINGER_TEAM_1_BOX_CORNERS[0][0][1] + (BOT_WINGER_TEAM_1_BOX_CORNERS[0][1][1] - BOT_WINGER_TEAM_1_BOX_CORNERS[0][0][1]) // 3],

    [BOT_WINGER_TEAM_1_BOX_CORNERS[1][0][0] + (BOT_WINGER_TEAM_1_BOX_CORNERS[1][1][0] - BOT_WINGER_TEAM_1_BOX_CORNERS[1][0][0]) * 2 // 3,
    BOT_WINGER_TEAM_1_BOX_CORNERS[1][0][1] + (BOT_WINGER_TEAM_1_BOX_CORNERS[1][1][1] - BOT_WINGER_TEAM_1_BOX_CORNERS[1][0][1]) // 3],
]

BOT_WINGER_MIN_DIST_TO_TEAMMATE_TO_PASS = 100
BOT_WINGER_MAX_DIST_TO_TEAMMATE_TO_PASS = 240
BOT_WINGER_DANGEROUS_DIST_TO_ENEMY = 50
BOT_WINGER_DIST_TO_SCORE = 350

# Striker

BOT_STRIKER_TEAM_0_BOX_CORNERS = [
    [CORNERS[0], CORNERS[2]]
]
BOT_STRIKER_TEAM_1_BOX_CORNERS = [
    [CORNERS[0], CORNERS[2]]
]

BOT_STRIKER_TEAM_0_INITIAL_POS = [
    [CORNERS[0][0] + (CORNERS[2][0] - CORNERS[0][0]) * 2 // 7,
    (CORNERS[0][1] + CORNERS[2][1]) // 2]
]
BOT_STRIKER_TEAM_1_INITIAL_POS = [
    [CORNERS[0][0] + (CORNERS[2][0] - CORNERS[0][0]) * 5 // 7,
    (CORNERS[0][1] + CORNERS[2][1]) // 2]
]

BOT_STRIKER_MIN_DIST_TO_TEAMMATE_TO_PASS = 120
BOT_STRIKER_MAX_DIST_TO_TEAMMATE_TO_PASS = 280
BOT_STRIKER_DANGEROUS_DIST_TO_ENEMY = 50
BOT_STRIKER_DIST_TO_SCORE = 450

BOT_STRIKER_DIST_TO_NOTICE_ENEMY = 150
BOT_STRIKER_DANGEROUS_ENEMY_HEIGHT = 100

# Goalkeeper

BOT_GOALKEEPER_SPEED = 2

BOT_GOALKEEPER_TEAM_0_BOX_CORNERS = [
    [GATES[0][0], [GATES[0][1][0] + 50, GATES[0][1][1]]]
]
BOT_GOALKEEPER_TEAM_1_BOX_CORNERS = [
    [[GATES[1][0][0] - 50, GATES[1][0][1]], GATES[1][1]]
]

BOT_GOALKEEPER_TEAM_0_INITIAL_POS = [GATES_CENTER[0]]
BOT_GOALKEEPER_TEAM_1_INITIAL_POS = [GATES_CENTER[1]]
